# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_visit_date',
            field=models.DateTimeField(blank=True, verbose_name='date visited'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='reg_date',
            field=models.DateTimeField(blank=True, verbose_name='date registrated'),
        ),
    ]
