# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170920_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='allowed_date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='allowed_date_from'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='allowed_date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='allowed_date_to'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_visit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date visited'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='reg_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date registrated'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='time_from'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='time_to'),
        ),
    ]
