# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170920_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='time_to',
        ),
        migrations.AddField(
            model_name='visitor',
            name='allowed_time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='allowed_time_from'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='allowed_time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='allowed_time_to'),
        ),
    ]
