# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170920_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='allowed_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='allowed_date_from'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='allowed_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='allowed_date_to'),
        ),
    ]
