# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170920_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile_pics/avatar.png', null=True, upload_to='images/profile_pics/'),
        ),
    ]
