# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170922_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='similarity',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10),
        ),
    ]
